name: outliers_removal
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=4
  - alsa-lib=1.2.14
  - attr=2.5.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - ceres-solver=2.2.0
  - colmap=3.11.1
  - contourpy=1.3.2
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - double-conversion=3.3.1
  - eigen=3.4.0
  - flann=1.9.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.2.2
  - freeimage=3.18.0
  - freetype=2.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - glew=2.1.0
  - glib=2.86.1
  - glib-tools=2.86.1
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - icu=75.1
  - imath=3.1.12
  - jasper=4.2.8
  - jxrlib=1.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libamd=3.3.3
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.76
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp21.1=21.1.5
  - libclang13=21.1.5
  - libcolamd=3.3.4
  - libcups=2.3.3
  - libcurl=8.17.0
  - libcxsparse=4.4.1
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.1
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - libllvm21=21.1.5
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopus=1.5.2
  - libparu=1.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=18.0
  - libraw=0.21.4
  - librbio=4.3.4
  - libsndfile=1.2.2
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=257.9
  - libtiff=4.7.1
  - libumfpack=6.3.5
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - metis=5.1.0
  - mpfr=4.2.1
  - mpg123=1.32.9
  - munkres=1.1.4
  - ncurses=6.5
  - nspr=4.38
  - nss=3.117
  - openexr=3.2.2
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.3
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - suitesparse=7.10.1
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - tornado=6.5.2
  - unicodedata2=17.0.0
  - vlfeat=0.9.21
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - av==16.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - bleach==6.3.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorlog==6.10.1
      - comet-ml==3.54.0
      - comm==0.2.3
      - configargparse==1.7.1
      - configobj==5.0.9
      - cryptography==46.0.3
      - dash==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.4.0
      - docstring-parser==0.17.0
      - dulwich==0.24.8
      - embreex==2.17.7.post7
      - everett==3.1.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fire==0.7.1
      - flask==3.1.2
      - fpsample==0.3.3
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - gsplat==1.4.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lxml==6.0.2
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - msgspec==0.19.0
      - multiprocess==0.70.18
      - narwhals==2.10.2
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfstudio==1.1.5
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nodeenv==1.9.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nuscenes-devkit==1.2.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - open3d==0.19.0
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parso==0.8.5
      - pathos==0.3.4
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - plotly==6.4.0
      - plyfile==1.1.3
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pycollada==0.9.2
      - pycolmap==3.12.6
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pymeshlab==2025.7
      - pyngrok==7.4.1
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-engineio==4.12.3
      - python-json-logger==4.0.0
      - python-socketio==5.14.3
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rawpy==0.25.1
      - referencing==0.37.0
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rtree==1.4.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.43.0
      - shapely==2.0.7
      - shtab==1.7.2
      - simple-websocket==1.1.0
      - simplejson==3.20.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - splines==0.3.0
      - stack-data==0.6.3
      - svg-path==7.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorly==0.9.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.6.7
      - tinycss2==1.4.0
      - tomli==2.3.0
      - torch==2.9.0
      - torch-fidelity==0.3.0
      - torchmetrics==1.8.2
      - torchvision==0.24.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.9.0
      - triton==3.5.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - vhacdx==0.0.9
      - viser==0.2.7
      - wadler-lindig==0.1.7
      - wandb==0.22.3
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - wrapt==2.0.0
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xatlas==0.0.11
      - xxhash==3.6.0
      - yourdfpy==0.0.58
      - zipp==3.23.0
prefix: /home/user/.conda/envs/outliers_removal
